import fs from 'fs';
import path from 'path';
import yaml from 'yaml';
import pc from 'picocolors';

export function generateDocs(targetDir: string) {
  console.log(pc.cyan(`\n📚 Generating workflows documentation in: ${targetDir}\n`));

  if (!fs.existsSync(targetDir)) {
    console.error(pc.red(`Error: Target directory ${targetDir} does not exist.`));
    return;
  }

  const manifests = findManifests(targetDir);

  if (manifests.length === 0) {
    console.log(pc.yellow('No workflows found. Cannot generate documentation.'));
    return;
  }

  let markdown = `# Workflows Registry

This file is automatically generated by running \`money-engine docs\`.

## Available Workflows

| Category | Workflow / ID | Version | Status | Risk Level | Human Approval | Required Integrations |
| :--- | :--- | :---: | :---: | :---: | :---: | :--- |
`;

  for (const manifestPath of manifests) {
    try {
      const content = fs.readFileSync(manifestPath, 'utf8');
      const manifest = yaml.parse(content);
      
      const id = manifest.id || path.basename(path.dirname(manifestPath));
      const name = manifest.name || 'Unknown';
      const category = manifest.category || 'Unknown';
      const version = manifest.version || '0.1.0';
      const status = manifest.status || 'unknown';
      const risk = manifest.risk_level || 'unknown';
      const humanApproval = manifest.human_approval_required ? 'Yes' : 'No';
      const integrations = (manifest.required_integrations || []).join(', ');

      const workflowLink = `[${name}](${category}/${id})`;

      markdown += `| **${category}** | ${workflowLink} <br>\`(${id})\` | ${version} | \`${status}\` | \`${risk}\` | ${humanApproval} | ${integrations} |\n`;
    } catch (e: any) {
      console.log(pc.red(`Failed to parse ${manifestPath}: ${e.message}`));
    }
  }

  markdown += `\n---

*To add new workflows, check out [CONTRIBUTING.md](../CONTRIBUTING.md).*
`;

  const outputPath = path.join(targetDir, 'README.md');
  try {
    fs.writeFileSync(outputPath, markdown, 'utf8');
    console.log(pc.green(`✔ Workflows directory README generated successfully at: ${outputPath}\n`));
  } catch (e: any) {
    console.error(pc.red(`Error: Failed to write documentation - ${e.message}`));
  }
}

function findManifests(dir: string): string[] {
  const manifests: string[] = [];

  function traverse(currentDir: string) {
    const files = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const file of files) {
      const fullPath = path.join(currentDir, file.name);
      if (file.isDirectory()) {
        if (file.name !== 'node_modules' && file.name !== 'dist' && !file.name.startsWith('.')) {
          traverse(fullPath);
        }
      } else if (file.name === 'manifest.yaml' || file.name === 'manifest.yml') {
        manifests.push(fullPath);
      }
    }
  }

  traverse(dir);
  return manifests;
}
